src/objects/PE_Logger__c.object
<CustomObject>
    <fields>
        <fullName>PE_JSON__c</fullName>
        <description>json for PE</description>
        <label>PE JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <description>Unique Id for the PE</description>
        <label>Unique Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PE Logger</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>PE Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PE Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PERetryBatch.cls
/**
 * @description       : Batch class that can be used to retry platform events that fail
 * @author            : Rajesh Ramachandran
 * @group             : 
 * @last modified on  : 02-08-2021
 * @last modified by  : Rajesh Ramachandran
 * Modifications Log 
 * Ver   Date         Author                Modification
 * 1.0   02-08-2021   Rajesh Ramachandran   Initial Version
**/
public without sharing class PERetryBatch implements Database.Batchable<SObject>{

    String peQuery;
    List<SObject> retryPEs = new List<SObject>();

    //retry events in the last day
    public PERetryBatch(){
        peQuery = 'Select id, unique_id__c,PE_JSON__c,PE_Name__c,Retry_PE__c from PE_Logger__c where Retry_PE__c = true and status__c = \'Pending\' and Createddate = last_n_days:1';
    }    

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(peQuery);
    }

    public void execute(Database.BatchableContext bc, List<PE_Logger__c> records){

        if (records != null && records.size() > 0){
            PERetryPublisher retryCls = new PERetryPublisher(records);
            retryCls.run();
        }
        //reset the processed pe loggers to retry = false
        for (PE_Logger__c pel : records){
            pel.retry_pe__c = false;
        }
        update records;

    }

    public void finish(Database.BatchableContext bc){
        //add any fnish logic specific to org
    }

}